kind: Pod
apiVersion: v1
metadata:
  name: env
spec:
  containers:
  - name: nginx
  - image: nginx
    env:
    - name: course
      value: DevOps
    - name: Trainer
      value: "Rajabhushanam yeguru"
    - name: duration
      value: "120 hrs"
         